version: '3.8'
services:
  horusdemod:
    build:
      context: .
      target: prod
    image: 'projecthorus/horusdemodlib:latest'
    #read_only: true
    device_cgroup_rules:
      - 'c 189:* rwm'
    env_file:
      - ./user.env
    command: 'bash -c $${DEMODSCRIPT}'
    volumes:
      - type: 'tmpfs'
        target: '/tmp'
      - './user.cfg:/user.cfg'
      - '/dev/bus/usb:/dev/bus/usb'

